"""init

Revision ID: 4789d270fe46
Revises: dc0931d7c0ac
Create Date: 2024-03-11 16:13:08.110006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4789d270fe46"
down_revision: Union[str, None] = "dc0931d7c0ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_billing",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("sent_email", sa.Boolean(), nullable=False),
        sa.Column("is_payment", sa.Boolean(), nullable=False),
        sa.Column("award", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "bookkeeping_board", sa.Column("used_in_billing", sa.Boolean(), nullable=False)
    )
    op.drop_column("bookkeeping_board", "is_payment")
    op.drop_column("bookkeeping_board", "sent_email")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookkeeping_board",
        sa.Column("sent_email", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookkeeping_board",
        sa.Column("is_payment", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("bookkeeping_board", "used_in_billing")
    op.drop_table("daily_billing")
    # ### end Alembic commands ###
