"""add is_billing

Revision ID: 145b43a11624
Revises: 7a420cb425ed
Create Date: 2024-03-10 01:50:57.023836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import false

# revision identifiers, used by Alembic.
revision: str = "145b43a11624"
down_revision: Union[str, None] = "7a420cb425ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_board",
        sa.Column("is_billing", sa.Boolean(), nullable=False, server_default=false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_board", "is_billing")
    # ### end Alembic commands ###
